### ISSUE TITLE
cleaning up

### ISSUE THREAD

**Issue by ghost** [yuk7/CentWSL#1]
Hi,

This is how I messed it up :
 
1- installed successfully
2- deleted the whole installation directory just manually!
3- trying to clean it and it doesn't work.

wondering how to clean it up or re-install. It says:

> .\CentOS.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005

OS 	 Windows 10 Enterprise
Version	10.0.17134 Build 17134

**Comment by MDITSD** [comment]
try 
`CentOS.exe clean`

**Comment by ghost** [comment]
I did. It says: 

`ERROR:[CentOS]` is not installed.

**Comment by MDITSD** [comment]
Try:

Regedit:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss

There´s probably a subfolder for your CentWSL.
Delete that folder. Careful, don't delete folders of other wsl-installations

**Comment by yuk7** [comment]
Please try 
`wslconfig /u CentOS` command.
This can be forced to unregister.

**Comment by ghost** [comment]
> wslconfig /u CentOS
> There is no distribution with the supplied name.
> 

> wslconfig /l
> Windows Subsystem for Linux Distributions:
> Legacy (Default)
> 

I also do not have this location in registry HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss

**Comment by yuk7** [comment]
Where did you deploy the installer?
It should be kept in mind that it can not be installed except for C drive.

https://github.com/yuk7/wsldl/wiki/Error-codes-list#0x80070003

**Comment by yuk7** [comment]
Also, it can not be installed in a directory without full access.

**Comment by ghost** [comment]
I ran Powershell as admin and managed to install it. I thought I installed it first time without admin privileges?
It's installed now but running it also requires to be done as admin and logged in user is now root.

**Comment by yuk7** [comment]
Do not use administrator privileges during installation.
Please setting for allow full access to the directory.

**Comment by yuk7** [comment]
For example, "Program Files" can not normally be written by users, so it needs to be set up.
Therefore I recommend installing to the user directory.

**Comment by ghost** [comment]
It's under a user directory in C drive. If I do not run it as admin the HRESULT:0x80070005 error will appear. I suspect it's due to a previous installation which it's not able to clean up.

**Comment by gabrielcabana21** [comment]
Hi!
I installed CentWSL on the Desktop, and then made it my default WSL distro with `wsl /s CentOS`. I would like to uninstall it npw. Unfortunately, I can't use `wsl /u CentOS` or `wsl /unregister CentOS`. I always get `/bin/bash: /unregister: No such file or directory`. Does anyone have insight into the issue please?

**Comment by David-OConnor** [comment]
> 
> 
> Please try
> `wslconfig /u CentOS` command.
> This can be forced to unregister.

Thanks bro; fixed it for me.
