### ISSUE TITLE
Getting error when setting the default user

### ISSUE THREAD

**Issue by ZamzamMumin** [yuk7/CentWSL#10]
C:\Users\zmumin\Documents\WSLDistro\CentOS>centos.exe config --default-user zmumin
ERROR
HRESULT:0x80004005
Press any key to continue...

Kindly help!
I am running command prompt in administrator mode.

**Comment by yuk7** [comment]
Would you like to try `centos.exe config --default-uid` instead?

**Comment by yuk7** [comment]
You need to create the user manually.
