### ISSUE TITLE
dose it can use xshell to connect？

### ISSUE THREAD

**Issue by KeZhimin** [yuk7/CentWSL#12]
like WSL ubuntu，I can use xshell to connect it。but now，i set the CentWSL in the same way like WSL Ubuntu，but I still can not connect it with xshell...   the command line replay： Failed to get D-Bus connection: Operation not permitted

**Comment by zfk513** [comment]
can you start the service , i think it is a systemctl problem

**Comment by yuk7** [comment]
This is duplicated issue, so please move to:
https://github.com/yuk7/CentWSL/issues/11
