### ISSUE TITLE
Yum update fails

### ISSUE THREAD

**Issue by randombitsUK** [yuk7/CentWSL#13]
When I install and start CentWSL, I then generally do a `yum update`. However this then fails due to verion problems between glibc-common i686 and x86_64.

I assume this happens for everyone, as at this point it's the basic instance of CentOS? Any idea how to resolve it?

```Protected multilib versions: glibc-2.17-260.el7_6.6.x86_64 != glibc-2.17-260.el7_6.5.i686```

P.S. Thanks for creating this - it's been a huge boon. Also, I previously set this up a few months ago without any issue - but now it doesn't matter if I use the latest release, or the one I used last time - both error.

**Comment by yuk7** [comment]
I could not confirm the problem.
But,Please try:
```
yum clean all
package-cleanup --cleandupes
```

**Comment by randombitsUK** [comment]
Thanks for replying - but that still doesn't appear to fix the issue. 

However I'll detail what I doing in more detail in case that helps.

1. I download the zip file: https://github.com/yuk7/CentWSL/releases/download/7.0.1905.1/CentOS.zip
1. I create a directory: D:\Apps\wsl\CentOS
1. I copy the zip file into the above directory, and unpack it (creating CentOS.exe and rootfs.tar.gz).
1. I delete the zip file
1. I double click on CentOS.exe and it says 'installing...'
1. Once that's finished, I close the window and double click on CentOS.exe again.
1. At the command line in CentOS, running 'yum update' results in the error above.

I tried your suggestions, to no effect, and the output is here:
```
[root@DESKTOP... ~]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: base extras updates
[root@DESKTOP... ~]# package-cleanup --cleandupes
Loaded plugins: fastestmirror
No duplicates to remove
```

I should also say, I don't get the error I reported straight away, here are the steps that lead to it.
1. Run `yum update`
2. It reports back
```
...
Install   1 Package  (+1 Dependent package)
Upgrade  28 Packages

Total download size: 160 M
Is this ok [y/d/N]: y
```
3. On selecting 'y' it downloads the packages
4. I'm asked to confirm the GPG key for:
```
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
```
5. On clicking yes it runs the transactions
```
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : tzdata-2019b-1.el7.noarch                                                                                                                   1/58
  Updating   : glibc-common-2.17-260.el7_6.6.x86_64                                                                                                        2/58
```
6. It just hangs at this point
7. I use CTRL+C to terminate
8. I run `yum update` again
9. Now I see the warning:
```
Protected multilib versions: glibc-2.17-260.el7_6.6.x86_64 != glibc-2.17-260.el7_6.5.i686
```
