### ISSUE TITLE
WSL2

### ISSUE THREAD

**Issue by anvar-sadikhov** [yuk7/CentWSL#15]
How to activate WSL2 on CentWSL? Thanks

**Comment by matthiasballreich** [comment]
any news? For me it did not work, too with WSL2.

**Comment by engibeer** [comment]
Works fine for me, though I get memory leaks

**Comment by yuk7** [comment]
This issue is [WSL#4371](https://github.com/microsoft/WSL/issues/4371)
Fixed in 18970
