### ISSUE TITLE
WLS2 Docker

### ISSUE THREAD

**Issue by ghost** [yuk7/CentWSL#16]
Anyone have succefully run Docker with CentOS in WLS2?
I get error related to d-bus/systemctl

After I have try:
Try https://github.com/gdraheim/docker-systemctl-replacement 

And this kind of error :
-bash-4.2# docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Comment by zfk513** [comment]
I met the same when i want to start MySQL

**Comment by yuk7** [comment]
If you use WSL2,you can use [genie](https://github.com/arkane-systems/genie).
This can run systemd daemon.

**Comment by yuk7** [comment]
Since the service can't be automatically excuted,it is necessary to start the service manually.
`systemctl start docker`
