### ISSUE TITLE
--default-user

### ISSUE THREAD

**Issue by adamdoyle** [yuk7/CentWSL#2]
I'm running `CentOS.exe config --default-user someuser` to set the default user to "someuser".

It doesn't show any output (but if I replace "someuser" with a user that doesn't exist, I get an error).

When I run CentOS.exe, it still just defaults to "root" instead of "someuser".

Am I doing something wrong?

**edit:** fixed typo in command

**Comment by yuk7** [comment]
Please reboot your computer

**Comment by MDITSD** [comment]
Use the following command: `CentOS.exe config --default-user someuser`

**Comment by adamdoyle** [comment]
@Bahaco yeah there's a typo in my original question, but I _had_ included `config` when I originally tried it.  @yuk7 The reboot might be what I was missing.  I'll try when I get home later today.  Thanks.

**Comment by adamdoyle** [comment]
I keep forgetting to try this when I get home.  I'm going to close the issue, because the reboot suggestion seems pretty likely to be what I was missing.  I'll reopen if the problem persists.

Thanks again for your help.

**Comment by adamdoyle** [comment]
Rebooting **did** fix the issue.  (in case anyone has same issue)
