### ISSUE TITLE
Where it installed?

### ISSUE THREAD

**Issue by zfk513** [yuk7/CentWSL#21]
Hi,green hand in linux and already met a dozen of problem,cuz it is based on the same PC, want to copy directly ,but i couldn't find where it installed,thx a lot !谢谢

**Comment by zfk513** [comment]
I think i find it ,just in the installed package ,but how could i restart the centos?
It didn't work

**Comment by zfk513** [comment]
OK after a minute closed the windows ,it update hhh

**Comment by yuk7** [comment]
Ok. I'm relieved to hear that! よかった!
