### ISSUE TITLE
Sorry but how to start a mysql service

### ISSUE THREAD

**Issue by zfk513** [yuk7/CentWSL#22]
![image](https://user-images.githubusercontent.com/29036702/68259867-04822380-0076-11ea-8a16-6e6b336b33dd.png)
I already [#issue WSL](https://github.com/microsoft/WSL/issues/3905) [repleaceService ](https://github.com/RoliSoft/WSL-Distribution-Switcher/issues/72) [using systemctl](https://github.com/Microsoft/WSL/issues/1579#issuecomment-271555310)
But all failed ,could you help?thx a lot ? ありがとうございます

**Comment by yuk7** [comment]
Which mysql version are you using?
If you use Mysql 8.0 or later,I think [this isssue](https://github.com/Microsoft/WSL/issues/3631) may be related.

**Comment by zfk513** [comment]
well just 5.7

**Comment by yuk7** [comment]
Ok.
Can you excute `mysqld` command?
You can see a detailed log.

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/68265933-72374b00-0088-11ea-96cd-35198f14c59f.png)
I think the problem is i still cannot get a service

**Comment by yuk7** [comment]
Yes,`mysqld` is mysql daemon executable,it provides mysql server service.
Since an execution user error has occurred, try switching to the mysql user and retry it.

```
su mysql
mysqld
```

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/68267767-8716dd00-008e-11ea-8895-3ddf0fff4587.png)
the same,i decide try Vmare now ,thx a lot

**Comment by yuk7** [comment]
Did you make initial settings including mysql_secure_installation?

**Comment by zfk513** [comment]
> Did you make initial settings including mysql_secure_installation?

Nope,i just install and try to start the service as other tutorial suggest,how to change ?

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/68268250-6b143b00-0090-11ea-85a0-4334eaa9055a.png)
the VMware ways works ,so far ,thank you for you attention

**Comment by yuk7** [comment]
hmm... I did same,but it worked.

Env: Windows 10 1903
![screenshot](https://user-images.githubusercontent.com/29954265/68270111-a407dc00-009f-11ea-8c17-9346ec3d82b4.png)

**Comment by zfk513** [comment]
how so,i just cann't ????

**Comment by yuk7** [comment]
Can you read /var/log/journal/mysqld.service.log ?

**Comment by zfk513** [comment]
yeap
![image](https://user-images.githubusercontent.com/29036702/68292813-a67e2c00-00c7-11ea-8696-46f5bed1d97e.png)

**Comment by yuk7** [comment]
Ok... It seems crashed mysqld daemon.
Logs are stored elsewhere.
Please read /var/log/mysqld.log

**Comment by parveenhooda** [comment]
![image](https://user-images.githubusercontent.com/57480496/68376143-35f50f00-019c-11ea-9f12-d3a462ff0aac.png)

This is happening because /var/run is a volatile directory and somehow it is not able to find/create mysqld.pid file in /var/run/mysqld and hence it is failing. If it still doesn't work look for the logs at /var/logs/mysqld.log. 

Also, you would have to do it every time you restart the LxssManager service or reboot the machine.

![image](https://user-images.githubusercontent.com/57480496/68376261-6fc61580-019c-11ea-8853-5fdbff44c60b.png)

**Comment by mandaputtra** [comment]
@parveenhooda, @yuk7  what distro youre using? seems you can get your `systemctl` works, I can't get `systemctl` works on Ubuntu 18.04. Thanks


Edit : Sorry stupid me asking without even realize this was a CentOS WSL Repo

**Comment by yuk7** [comment]
@mandaputtra 
systemctl alternative script
Please see: https://github.com/Microsoft/WSL/issues/1579#issuecomment-481085323
