### ISSUE TITLE
Cannot get CentOS back after uninstalling

### ISSUE THREAD

**Issue by ThomasArmstrongJr1247** [yuk7/CentWSL#23]
I have tried to follow the directions for a clean uninstall but I keep getting the error message to make sure to reinstall, if it even starts at all. Most recently when I click the .exe it just shows a fast console open and close. Please help me correct this. I am running Windows Server 2019. It all crashed when I unsuccessfully tried to install and use GNOME desktop and Graphical User Interface Groups with this distro. Please and thank you!

**Comment by ThomasArmstrongJr1247** [comment]
Edit: I was able to reinstall correctly by deleting the Registry Keys. However, am still having issue getting a GUI Desktop running, is this possible with this distro?

**Comment by yuk7** [comment]
You need to install an X server for Windows and set it to WSL.
