### ISSUE TITLE
CentOS 6?

### ISSUE THREAD

**Issue by chrisplusplus** [yuk7/CentWSL#24]
Can you make one for Centos 6 please?  Or if anyone can provide me with instructions on how to do so.  Thanks!

**Comment by yuk7** [comment]
I created [6.0.1907.0](https://github.com/yuk7/CentWSL/releases/tag/6.0.1907.0)
but not tested yet.

**Comment by yuk7** [comment]
I tried for it. But it not works.
Maybe it is impossible.

LXCore kernel crashed with an error.
