### ISSUE TITLE
Virus alert while installing

### ISSUE THREAD

**Issue by nnsense** [yuk7/CentWSL#26]
I'm sure Microsoft antivirus alert is a false positive, but I though it was anyway important to report this. While installing, Microsoft AV flagged as sever threat both 
```
.\CentOS7\rootfs\usr\bin\dbus-daemon
```
and
```
.\CentOS7\rootfs\usr\bin\systemctl
```
as affected by `Trojan:Win64/Longage`.

Thanks

**Comment by yuk7** [comment]
Did it resolve? 
I use Windows Defender, but I haven't found any false positives.

**Comment by assanges** [comment]
See also the [CentOS forum](https://forums.centos.org/viewtopic.php?t=72781) although a different rpm, mostly a false positive ('coz it's the dbus-demon and systemctl, eh!?) and should've been removed by Microsoft during definition update.
.
いつもお世話いただいて、感謝の気持ちでいっぱいです。 <(_ _)>

**Comment by roberttakacs** [comment]
Same here, CentOS7.exe blocked and labeled 'Insight Network Threat' by Norton

**Comment by rftaka** [comment]
Same here, blocked and labeled 'Network Threat' by Norton

**Comment by yuk7** [comment]
exe?

**Comment by rftaka** [comment]
Yep

**Comment by yuk7** [comment]
I tested with VirusTotal, I found that some engines detected it as malware.
Executable files with icon resources were found to be easily detected as malware.

**Comment by yuk7** [comment]
I don't have Norton.
I would be grateful if you could help report a false positive.
https://support.norton.com/sp/en/us/home/current/solutions/kb20100222230832EN

I'll report false positives of some AV vendors whenever possible.

**Comment by rftaka** [comment]
> I don't have Norton.
> I would be grateful if you could help report a false positive.
> https://support.norton.com/sp/en/us/home/current/solutions/kb20100222230832EN
> 
> I'll report false positives of some AV vendors whenever possible.

Done that
