### ISSUE TITLE
Restore procedure

### ISSUE THREAD

**Issue by rovall** [yuk7/CentWSL#28]
Hi,
I need to migrate my installation from one laptop to another. I have made backup.tar.gz on the old laptop using CentOS7.exe, moved it together with CentOS7.exe to the new laptop... and what next?

Trying to launch just CentOS7.exe results in error:
```
C:\CentOS>CentOS.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...
```
I tried downloading Launcher.exe - same issue.
I have re-downloaded the whole distribution and it installed successfully. After manually unpacking backup.tar.gz and replacing rootfs folder, I get this:
```
C:\CentOS>CentOS7.exe
Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution...
The specified network name is no longer available.
```

Could you please write a bit about **restore** procedure? In the README maybe. I think it would be helpful.

**Comment by yuk7** [comment]
Please rename backup.tar.gz to rootfs.tar.gz and execute exe.
You can install from backup file.

**Comment by yuk7** [comment]
Please execute this command:
```
CentOS.exe install backup.tar.gz
```

or 

rename `backup.tar.gz` to `rootfs.tar.gz` and execute exe for installation.

**Comment by rovall** [comment]
Hi,
Thank you for your answer, but I have described what happens when I do
exactly what you asked me to do. An attempt ends in error.

**Comment by yuk7** [comment]
What is error code?
Could you uninstall instance and retry...?
`wslconfig /u CentOS7`

**Comment by rovall** [comment]
That was a completely new installation of Windows. And I have already
solved it using LxRunOffline utility, so I'm not sure I can reproduce the
problem.

But that's probably good to know for others that you can specify an archive
in an "install" command.

**Comment by yuk7** [comment]
Ok.
