### ISSUE TITLE
how to install in non-admin user?

### ISSUE THREAD

**Issue by fly-potato-100** [yuk7/CentWSL#29]
In some reason i had to use wsl in non-admin user.
Then i got HRESULT:0x80070005. So how can i install this distro correctly??
Thanks for reading.

**Comment by yuk7** [comment]
Where do you installed it to?
It will probably work if you put it in a directory with full permissions and ownership.

**Comment by fly-potato-100** [comment]
> Where do you installed it to?
> It will probably work if you put it in a directory with full permissions and ownership.

I extracted the CentOS7.zip to `C:\CentOS7\` and ran the EXE directly, then got the failure info as above.

I'm thinking that perhaps I should install it under my home DIR(e.g.  C:\Users\XXX) or somewhere else??

I'm going to have a try next week.

**Comment by fly-potato-100** [comment]
@yuk7 Apologies for the delayed response.

Installing the distro to the non-admin user's home dir worked for me.

Thanks for the tips : )
