### ISSUE TITLE
Error: 0x80070005 before installation

### ISSUE THREAD

**Issue by hummeleBop** [yuk7/CentWSL#3]
Hi there,

Windows 10 1909, OS Build 17763.504

1- When I launch CentOS.exe, I get the following error:
```
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...
```

2- Do you plan to release the source code of the CentOS.exe ?

Bye

**Comment by yuk7** [comment]
1. Where do you install to?
It can install only to System Drive(C:).
2. source code is available on https://git.io/wsldl

**Comment by subhead** [comment]
I had the same problem, turned out that i needed to run centos.exe as administrator.

**Comment by tbela99** [comment]
> 
> 
> I had the same problem, turned out that i needed to run centos.exe as administrator.

that fixed the problem for me.
Thanks
