### ISSUE TITLE
[Question] Updating

### ISSUE THREAD

**Issue by lucasvc** [yuk7/CentWSL#32]
I've been using this WSL distro and I'm really fan!
But I have a few questions about this. If there is any mailing list, feel free to close it and point it to me.

1. I see new releases, but what is being updated? CentOS? `.exe` file?
1. I usually update my distro (in this case with `yum`). Should I also update **the whole package** when here it is a new version?

Thanks.

**Comment by yuk7** [comment]
1. Yes, the main change is the update of the exe.
There are also updates to packages installed by default.
2. Update of yum is update inside distro.
rootfs.tar.gz is used only during installation, so the update here is the update of the exe.

When updating exe, the file is included in icons.zip here.
https://github.com/yuk7/wsldl/releases/latest
