### ISSUE TITLE
how to re-register wsl?

### ISSUE THREAD

**Issue by Phamay** [yuk7/CentWSL#33]
hi, i reinstall my os, but i forget to backup the wsl, so how i re-register wsl, i don't wannt to reinstall it.
thanks!

**Comment by yuk7** [comment]
OK.  I'll help re-register.
What is the exe name?

**Comment by Phamay** [comment]
> OK. I'll help re-register.
> What is the exe name?

D:\hyper\CentOS7_WSL\CentOS7.exe
thanks

**Comment by yuk7** [comment]
[DELETED]
Ok. Download this file and apply reg file.
If you are using WSL1, use `Cent7-WSL1-FSv1.reg`.
If you are using WSL2, use `Cent7-WSL2.reg`.

**Comment by Phamay** [comment]
> [DELETED]
> Ok. Download this file and apply reg file.
> If you are using WSL1, use `Cent7-WSL1-FSv1.reg`.
> If you are using WSL2, use `Cent7-WSL2.reg`.
yeah it's good!
but there are losts of mistakes of permission errors,i thougt the rootfs extends windows permissions, so i have to reinstall wsl.
i dont't know is there any way to repaire it, thank you anyway.
