### ISSUE TITLE
How to use backup.tar.gz file ?

### ISSUE THREAD

**Issue by phamgiahung1368** [yuk7/CentWSL#35]
How to restore backup.tar.gz file ?

I have try to rename backup file to rootfs.tar.gz and it work, is this the right way to use it ?

**Comment by yuk7** [comment]
Yes.

You can rename to rootfs.tar.gz or run `CentOS.exe install backup.tar.gz` for restore backup.

**Comment by phamgiahung1368** [comment]
tks :D
