### ISSUE TITLE
ERROR:Installation Failed! HRESULT:0x80070569

### ISSUE THREAD

**Issue by mmahacek** [yuk7/CentWSL#42]
I get the same error when trying to install either the latest CentOS 7 or 8.  I am on the latest Insider Preview edition of Windows, and have tried both versions as myself and running as Administrator.

```
Installing...
ERROR:Installation Failed!
HRESULT:0x80070569
Press any key to continue...
```

**Comment by Kinatsu77** [comment]
You can install it by placing rootfs.tar.gz in the same hierarchy as CentOS8.exe and executing it with Administrator.

**Comment by yuk7** [comment]
Are other distros in your computer working?
WSL2 must have Intel-VT or AMD-V enabled.

**Comment by Kinatsu77** [comment]
Yes.
WSL2 have Intel-VT or AMD-V enabled.

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform

**Comment by mmahacek** [comment]
🤦‍♂️ note to self: don't try and run out of the ZIP file - extract it to a folder first.
