### ISSUE TITLE
Unatended registration: how to avoid hitting any key to continue...

### ISSUE THREAD

**Issue by Yanal-Yves** [yuk7/CentWSL#45]
Hello and Thank you for CentWSL !

I like automating everything and especially my laptop installation.
Here is the output when I register CentOS7 by calling the first time `CentOS7.exe` without parameter the first time:
```
PS C:\CentOS7> .\CentOS7.exe
Installing...
Installation Complete!
Press any key to continue...
```  

Is it possible to avoid the "Press any key to continue..." so that I can automate the registration ?

**Comment by yuk7** [comment]
Please use `install` argument.
`CentOS7.exe install`

**Comment by Yanal-Yves** [comment]
Thank you for your answer and thank you for this project !
I have updated my scripts :-)
Why is this option not showing up with `CentOS7.exe /?` ?
Could you update the readme and the help ?

**Comment by yuk7** [comment]
This command is undocumented, as I think it is not needed by the average user.
You can find it on the wsldl wiki.

**Comment by Yanal-Yves** [comment]
OK, thank you !
