### ISSUE TITLE
WSL and CentOS 6

### ISSUE THREAD

**Issue by linuxrebel** [yuk7/CentWSL#46]
Has anyone gotten CentOS 6 to work with WSL?  I've a feeling it won't.

**Comment by mishamosher** [comment]
I've tried, but it refuses to boot. The kernel used by CentOS 6 is _old_ (2.6 series), and so are all the other packages. Guess its just too old to be compatible with WSL. You can give it a try: https://github.com/mishamosher/CentOS-WSL/releases/tag/6.10-1907

**Comment by yuk7** [comment]
Yes, CentOS6 isn't compatible with WSL.
Please see #24 too.

**Comment by mishamosher** [comment]
Got it working on WSL2. I've updated the release notes linked in my previous comment with a how-to.

Install the WSL distro as usual, then update/create a `%USERPROFILE%\.wslconfig` file:
```
[wsl2]
kernelCommandLine = vsyscall=emulate
```
and restart the `LxssManager` Windows service (or restart the PC).

**Comment by linuxrebel** [comment]
@mishamosher  Let me see if I can duplicate your results. Thanks!

**Comment by linuxrebel** [comment]
I was able to verify that it works.  We have a rootfs built of a running system that is now a WSL-2 image.  @mishamosher thank you very much for this.
