### ISSUE TITLE
CentOS 8 @ WSL2 2004 - HRESULT:0x8000000d

### ISSUE THREAD

**Issue by Razva** [yuk7/CentWSL#47]
Hey,

I'm running W10 2004 and here's what I get when trying to run CentOS 8.1:

```powershell
Installing...
ERROR:Installation Failed!
HRESULT:0x8000000d
```

Do I need to mandatory run a higher Insider build?

Thank you!

**Comment by mishamosher** [comment]
The build you're trying to run is designed for containers and gives somewhat mixed results.

You might want to try [this CentOS 8 build](https://github.com/mishamosher/CentOS-WSL/releases/tag/8.2-2004).

**Comment by Razva** [comment]
> The build you're trying to run is designed for containers and gives somewhat mixed results.
> 
> You might want to try [this CentOS 8 build](https://github.com/mishamosher/CentOS-WSL/releases/tag/8.2-2004).

Will give that a try, thank you!
