### ISSUE TITLE
Do not know how to enter centos system

### ISSUE THREAD

**Issue by tlsalex** [yuk7/CentWSL#5]
I already finish bellow steps , and it shows me the installation is completed successfully
1. Download installer zip
2. Extract all files in zip file to same directory
3.Run CentOS.exe to Extract rootfs and Register to WSL

If I install ubuntu or kali linux from Microsoft store , I can launch them by click on the lunch button , but here , after the installation of centos , I don't how to launch it.

Sorry for stupid, I am not a programmer , just a normal user.

**Comment by tlsalex** [comment]
OK ， maybe I how it work now , start cmd or powershell console ,switch to the installation directory ,  then re-run centos.exe , correct ?
but why the installation did not add the installation directory to the path variable.

**Comment by yuk7** [comment]
Yes.
I prefer simple things,so I won't do it automatically

**Comment by zfk513** [comment]
> OK ， maybe I how it work now , start cmd or powershell console ,switch to the installation directory , then re-run centos.exe , correct ?
> but why the installation did not add the installation directory to the path variable.

pls tell me where is the installation directory ? i think the system is not store on the install folder

**Comment by yuk7** [comment]
Same directory as CentOS.exe
