### ISSUE TITLE
Can't uninstall or reinstall Centos7

### ISSUE THREAD

**Issue by okeyossai** [yuk7/CentWSL#50]
I have Windows 10 Pro Version 2004 (OS Build 19041.450)

1) I downloaded CentOS 7.6 1907 zip file to C:\users\myuser\Download and followed the installation instructions.

2) I removed the folder without cleaning it.

3) I then tried to clean it in Powershell using
./CentOS.exe clean

I got this error message

> ./CentOS.exe : The term './CentOS.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ./CentOS.exe clean
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./CentOS.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

4) I re-downloaded the zip file to C:\centos7

5) I unzipped and executed again but it doesn't run. It seems it is looking for the deleted folder

6) Now I'm not able to clean or re-install. How can I resolve this please

**Comment by ASlepushko** [comment]
Hello! You can type in powershell `wsl --unregister CentOS8` or any other distribution you use (to see distros type `wsl -l`) and then reinstall it by simply running centos.exe.
I hope this helps 😁

**Comment by okeyossai** [comment]
Wow!! Thank you so much @Alword . It worked like a charm. Thanks again.
