### ISSUE TITLE
Failed to set up default user'

### ISSUE THREAD

**Issue by dmahmutov** [yuk7/CentWSL#53]
Ive tried to execute <centos.exe config --default-user test> on CLI.
But I faced with `ERROR
HRESULT:0x80004005`

**Comment by hexmode** [comment]
Got this exact error.  But as #51 pointed out, you have to create the user inside using `adduser` before you can run `centos config --default-user _username_`

**Comment by hexmode** [comment]
It would be nice to have this in the documentation, @yuk7

**Comment by yuk7** [comment]
I wrote for user settings in readme.
