### ISSUE TITLE
CentOS8: Cannot get Any X Apps to Work with WSL2.

### ISSUE THREAD

**Issue by jasonmeverett** [yuk7/CentWSL#56]
Title says it. Can we not run X apps with WSL2 on CentOS8?

**Comment by yubelenky** [comment]
> Title says it. Can we not run X apps with WSL2 on CentOS8?

I believe WSL2 does not support X apps for any distro, not just for CentOS

**Comment by brandonrc** [comment]
Yes, you have to install extra software to get X support. 

https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2

You have several options but I really like X411 from the app store. It is nice clean and works well. You do have to pay for it but I really enjoy it. You have free options but you get what you pay for.
