### ISSUE TITLE
ssh can't start

### ISSUE THREAD

**Issue by liuping001** [yuk7/CentWSL#6]
Failed to get D-Bus connection: Operation not permitted

**Comment by troilus** [comment]
same

**Comment by yuk7** [comment]
WSL can not use systemd...

**Comment by Flyingrubberduck** [comment]
You can start the ssh deamon by using the option run:
centosexe run /usr/sbin/sshd

**Comment by graben** [comment]
Try https://github.com/gdraheim/docker-systemctl-replacement it will let you run `service sshd start`
