### ISSUE TITLE
This does not work - What is this? how does it work?

### ISSUE THREAD

**Issue by devlocalca** [yuk7/CentWSL#7]
I downloaded the .zip, I see CentOS.exe, now what?

If I double click CentOS.exe, I get the following:
```
c:\os\wsl\centos_wsl>.\CentOS.exe
Installation directory not found: .
Make sure it exists or reinstall.
Press any key to continue...
```
same when I run from the command line.

Is there a .tar anywhere for CentOS7 that will work if I do:   cmd>wsl --import <params>?

I just want CentOS to work under WSL.

**Comment by yuk7** [comment]
Please tell me
`wslconfig /l`
output?

**Comment by devlocalca** [comment]
This is the output:  I have installed several Linux distributions from the Windows Store, I am trying to get CentOS 7.1905 onto my Windows machine.  Thank You.
```
c:\>wslconfig /l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
kali-linux
SLES-12
Alpine
WLE
Debian
```

**Comment by yuk7** [comment]
Please excute
`CentOS.exe clean` command and
double click CentOS.exe ?
