### ISSUE TITLE
Use "Minimal" version as recommended by centos

### ISSUE THREAD

**Issue by N6REJ** [yuk7/CentWSL#8]
Please change this to the "minimal" version as recommended by centos.
![image](https://user-images.githubusercontent.com/1850089/60703357-35cfc480-9ec7-11e9-9f90-8942f6f2bfc6.png)
Also, a completion report showing whats what would be helpful.

**Comment by fumantsu** [comment]
It is not recommenced by centos. It is recommenced by Centos Web Panel which has nothing to do with centos.org. Maybe could be good as gives some freedom to installed whatever packages you want but some others (less hardcore) may want a working build "out of the box"
